language: r
sudo: false
cache: packages

r_binary_packages:
 - dplyr
 - magrittr
 - MASS
 - rmarkdown

after_failure:
  - ./travis-tool.sh dump_logs

env:
  - WARNINGS_ARE_ERRORS=1

notifications:
  email:
    on_success: change
    on_failure: change

notifications:
  slack:
    secure: IwEjNKm8jXWYMRcXlY9OtMphJs/PWqs1mE2SKLUzYRbo8dYnJ6LqqHVua+7nh/xZYu4hrq6NYDFg5vfDTAfIkvd66dP8UyerfSb9jCw+RkUzBKH6YTtlrmQdgbORvSsHY70G752cOGXkza8MWC7XJT0W7DFz1pg2gBsQHdsQ7cR3CdldxNjyaDM24HHAGKVsLVvBMUGb6Dmzvl4fXWk06MeU36+75NneBp8bMJg+dxZlyzilGPszTMitiEe3l1oKLWkOkvOgDuYpECWIYH6cw1tb4jrffR4DITzCMqaYEGXCZdGTFmd7xyNYcXX8fV3gYKukuvvkDgVOXP7TCchieigKkADfsJ05wnYWpppFP196iak0qtUmvZw63zz9GyfkNMQAmVOUt8GMwpowHUlu8q+aFAhZhUNBtY4MvWcnE3E9ltzUGxxCe/1eBstKUSudtnWEEGTQMSnp1nT7bdvZAUtRAYy2PmjIpZpMH+gChpnRcTcDZup7LHQ9wXke3i+JKkPnASrfQd+v+ugnBHqBJ6Oxzj1iFI3g2Ob7jXNPgeXLWDf0M65/BCjhE/3UFoOXN3h7WkTM2JMcmVw7uSVjdkhFdRUxhiCZrs/5GekEapWlFUcO284XUF5TXbx02PhswIZx9OO2hq1BvGjPGY9QC54U2BahDciMKbmn+AQ2Bvg=
