language: r
sudo: false
cache: packages

r_binary_packages:
 - dplyr
 - magrittr
 - MASS

after_failure:
  - ./travis-tool.sh dump_logs

env:
  - WARNINGS_ARE_ERRORS=1

notifications:
  email:
    on_success: change
    on_failure: change
